### ISSUE TITLE
climate data issues

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#127]
in `scripts/moti_climate.R` some have climate data but no `overall_rank`.  Not sure why but could be calculated in spreadsheet

- currently filters out by `overall_rank`.  
- could describe here which sites and if it makes sense to add.....

`erosion` and `embankment_issues` columns were renamed `erosion_issues` and  `embankment_fill_issues`  - were fltered out

**Comment by Mateo9569** [comment]
![image](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/assets/99455166/f860a35e-9940-43e7-b443-32caeb4be9a1)

There are two sites that do not have `overall_ranks` associated with them. The waterfall site on the main road (198116) and a phase 1 site on lemieux creek. The lemieux one has all the climate data filled out except for the `environmental_impacts` field, so that's why there is no overall rank. We could fill something in there?

As for the waterfall site, there is no climate change data at all filled out. Do you remember if you did that one? Maybe it's possible you filled it out on a paper form and not mergin?

**Comment by Mateo9569** [comment]
Update: I checked the photos of all the bulkley site cards that I put in onedrive. The Lemieux site had a value for `environmental_impacts` filled out on the card so I will add that to the csv and add that site to the overall results table. But as for the waterfall site, there is nothing filled out on the paper card either. I double checked the geopackage in Q and there's nothing there either. Oh well.
