### ISSUE TITLE
Perow hab con site names

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#2]
Perow Creek | 1801071_us is a ford I believe and probably should be `197653_us`

**Comment by Mateo9569** [comment]
There is also a hab con site that you and Vern did that you called 197653_us2. I think I remember what's going on now. We split up that habitat assessment. Tieasha and I did 500m upstream of the ford and you and Vern did 150m and we met up in the middle. So I should combine the data from both cards into one entry for 197653_us instead of two entries, correct?

**Comment by NewGraphEnvironment** [comment]
Could leave it as two sites for now.  We have ways to deal with that in the reporting because it is not uncommon to survey more than one site upstream and down of the same crossing
