### ISSUE TITLE
Add legend to waterfall creek image

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_bulkley_2022_reporting#72]
Wondering if this needs to be done or if your goal was to just give the reader an image showing the length we surveyed. It does say in the caption that the pink line is our habitat track.

**Comment by NewGraphEnvironment** [comment]
I think it is fine as is because the purpose of the map is to show where the tributary to Waterfall Creek actually flows as well as the location of the three culverts surveyed.  It will be the first time the stream location will be documented correctly as far I can tell.  "Surveyed" is spelled wrong in the caption though. will close once the spelling mistake is fixed
